obstacle1:
    type: "ellipsoid"
    radius: 0.175
    radius1: 0.175
    radius2: 0.175
    radius3: 0.175
    translation: [0,0,0.825]  # tx,ty,tz
    rotation: [0, 0, 0, 1] #qx,qy,qz,qw  
collision_pairs: 
    - ["elips_rob", "obstacle1"]


